Repository academiadev-jlle/frontend-thunderpets, pull requests merged in 2018-11, with the labels that each got.

#2 Refatoração da tela de cadastro de pet
  package-lock.json
  package.json
  src/App.vue
  src/components/GenderSelection.vue
  src/components/GoogleMap.vue
  src/components/ImageUpload.vue
  src/domains.js
  src/main.js
  src/views/Home.vue
  src/views/Post.vue
Labels: refactor, review

#6 #5 - Colocando tag de manifest no index.html
  public/index.html
Labels: refactor, review

#11 Feature/9
  package-lock.json
  src/App.vue
  src/router.js
  src/views/PostUser.vue
Labels: review

#12 Revert "Merge pull request #11 from academiadev-jlle/feature/9"
  package-lock.json
  src/App.vue
  src/router.js
  src/views/PostUser.vue
Labels: review

#13 Feature/8
  jest.config.js
  package-lock.json
  package.json
  src/components/GenderSelection.vue
  src/components/GoogleMap.vue
  src/components/PetCard.vue
  src/components/PetList.vue
  src/views/Home.vue
  src/views/Post.vue
  tests/unit/.eslintrc.js
  tests/unit/DrawerMenu.spec.js
  tests/unit/GenderSelection.spec.js
  tests/unit/GoogleMap.spec.js
  tests/unit/Home.spec.js
  tests/unit/ImageUpload.spec.js
  tests/unit/PetCard.spec.js
  tests/unit/PetList.spec.js
  tests/unit/Post.spec.js
  tests/unit/example.spec.js
Labels: review

#23 Feature/16
  .env.example
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/noPhoto.jpg
  src/components/GoogleMap.vue
  src/components/ImageUpload.vue
  src/components/Login.vue
  src/components/PetCard.vue
  src/components/PetList.vue
  src/domains.js
  src/main.js
  src/services/auth.js
  src/services/http.js
  src/services/pets.js
  src/services/users.js
  src/views/Home.vue
  src/views/Post.vue
Labels: config, enhancement, review

#24 Feature/9
  package-lock.json
  src/App.vue
  src/router.js
  src/views/PostUser.vue
Labels: review

#26 Release/3
  .env.example
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  src/App.vue
  src/assets/defaultImage.jpeg
  src/assets/noPhoto.jpg
  src/components/GenderSelection.vue
  src/components/GoogleMap.vue
  src/components/ImageUpload.vue
  src/components/Login.vue
  src/components/PetCard.vue
  src/components/PetList.vue
  src/domains.js
  src/main.js
  src/services/auth.js
  src/services/http.js
  src/services/pets.js
  src/services/users.js
  src/views/Home.vue
  src/views/Post.vue
  tests/unit/.eslintrc.js
  tests/unit/DrawerMenu.spec.js
  tests/unit/GenderSelection.spec.js
  tests/unit/GoogleMap.spec.js
  tests/unit/Home.spec.js
  tests/unit/ImageUpload.spec.js
  tests/unit/Login.spec.js
  tests/unit/PetCard.spec.js
  tests/unit/PetList.spec.js
  tests/unit/Post.spec.js
  tests/unit/example.spec.js
Labels: enhancement, review

#27 Atualizando branch de release
  package-lock.json
  src/App.vue
  src/router.js
  src/views/PostUser.vue
Labels: hotfix, review

#28 Feature/17
  README.md
  package-lock.json
  package.json
  src/App.vue
  src/components/ContactInfo.vue
  src/components/DrawerMenu.vue
  src/components/GenderChip.vue
  src/components/GoogleMap.vue
  src/components/ImageUpload.vue
  src/components/Login.vue
  src/components/PetCard.vue
  src/components/SizeChip.vue
  src/filters.js
  src/main.js
  src/router.js
  src/views/PetDetail.vue
  src/views/PostUser.vue
Labels: enhancement, review
