Repository academiadev-jlle/frontend-thunderpets, pull requests merged in 2018-12, with the labels that each got.

#32 Feature/18
  src/App.vue
  src/components/ContactInfo.vue
  src/components/Login.vue
  src/components/PetCard.vue
  src/components/PetList.vue
  src/router.js
  src/services/auth.js
  src/services/pets.js
  src/services/users.js
  src/store.js
  src/views/Post.vue
  src/views/User.vue
Labels: enhancement, review

#33 Feature/25
  package-lock.json
  src/components/UserContacts.vue
  src/views/Post.vue
  src/views/PostUser.vue
Labels: enhancement, review

#38 Feature/7
  package-lock.json
  package.json
  src/App.vue
  src/components/DrawerMenu.vue
  src/components/Entrance.vue
  src/components/PetCard.vue
  src/components/PetDetailComponent.vue
  src/components/PetDetailDialog.vue
  src/components/PetList.vue
  src/main.js
  src/router.js
  src/services/pets.js
  src/views/PetDetail.vue
  src/views/PostUser.vue
  src/views/Search.vue
Labels: enhancement, review

#43 Logins sociais
  package-lock.json
  package.json
  src/components/Entrance.vue
  src/components/FacebookButton.vue
  src/components/GoogleButton.vue
  src/components/Login.vue
  src/components/Register.vue
  src/services/http.js
  src/views/User.vue
Labels: enhancement, review

#48 Feature/41
  src/App.vue
  src/components/DrawerMenu.vue
  src/components/Entrance.vue
  src/components/GoogleMap.vue
  src/components/ImageUpload.vue
  src/components/Login.vue
  src/components/PetCard.vue
  src/components/PetList.vue
  src/components/UserContacts.vue
  src/domains.js
  src/filters.js
  src/router.js
  src/services/pets.js
  src/services/users.js
  src/views/Post.vue
  src/views/PostUser.vue
  src/views/User.vue
Labels: review

#49 Compartilhamento social
  package-lock.json
  package.json
  src/components/PetDetailComponent.vue
  src/components/PetDetailDialog.vue
  src/components/Register.vue
  src/components/SharingMenu.vue
  src/main.js
Labels: enhancement, review

#51 Feature/20
  package-lock.json
  src/App.vue
  src/components/FooterApp.vue
  src/components/MembersInfo.vue
  src/router.js
  src/views/MainPage.vue
Labels: review

#46 Publicação da plataforma no Heroku
  package-lock.json
  package.json
  server.js
Labels: review

#53 Feature/37
  package-lock.json
  package.json
  src/App.vue
  src/components/DrawerMenu.vue
  src/components/Entrance.vue
  src/components/Filters.vue
  src/components/FiltersForm.vue
  src/components/GenderSelection.vue
  src/components/MembersInfo.vue
  src/components/PetCard.vue
  src/components/PetList.vue
  src/domains.js
  src/main.js
  src/store.js
  src/views/MainPage.vue
  src/views/Search.vue
Labels: review

#52 Usuário que cadastrou o pet
  src/components/PetDetailComponent.vue
  src/components/PetDetailDialog.vue
  src/components/SharingMenu.vue
Labels: enhancement, review

#55 Arrumando alguns detalhes de geolocalização
  src/components/Filters.vue
  src/router.js
  src/views/PostUser.vue
  src/views/User.vue
Labels: hotfix, review

#56 Hotfix
  src/components/Filters.vue
Labels: review

#57 Solucionando problemas de filtros na tela inicial
  src/components/FiltersForm.vue
  src/router.js
Labels: review

#59 Tela de rota não encontrada (404)
  src/assets/404.png
  src/router.js
  src/views/NotFound.vue
Labels: review

#60 Recuperação de senha
  package-lock.json
  package.json
  src/components/Login.vue
  src/router.js
  src/services/users.js
  src/views/NotFound.vue
  src/views/PasswordRecovery.vue
Labels: enhancement, review

#62 #61 - Correções e ajustes de acordo com feedback
  src/App.vue
  src/components/DrawerMenu.vue
  src/components/Filters.vue
  src/components/FiltersForm.vue
  src/components/GoogleMap.vue
  src/domains.js
  src/views/Post.vue
  src/views/User.vue
Labels: review

#63 Refactor/61
  src/components/GoogleButton.vue
  src/components/ImageUpload.vue
Labels: review

#64 Refactor/61
  src/views/Post.vue
Labels: review
